#include "share/atspre_define.hats"
#include "share/atspre_staload.hats"
staload "libats/SATS/hashtbl_chain.sats"
staload _ = "libats/DATS/hashfun.dats"
staload _ = "libats/DATS/linmap_list.dats"
staload _ = "libats/DATS/hashtbl_chain.dats"
staload "libats/SATS/linmap_list.sats"
staload _ = "libats/DATS/linmap_list.dats"
staload "ats-result/src/SATS/result.sats"
staload ARG = "./../SATS/arg.sats"
staload ARGS = "./../SATS/lib.sats"
